### PR TITLE
ability to add custom methods

### PR DESCRIPTION
**Pull request by KhodorAmmar**

### CODE REVIEW

**Comment by colestrode** [comment]
Thanks for the PR @KhodorAmmar :) Do you have any thoughts about how this would be useful to people? Do you have any specific use cases in mind?

**Comment by KhodorAmmar** [comment]
We're developing a bot for our company slack team and we needed a way to save data which isn't related to teams, users, or channels. For example, any user can add a tip, the bot will save the list of tips and send random daily ones

**Comment by colestrode** [comment]
That's a cool idea :) I just double checked and Botkit will expose any additional methods on the underlying storage module, so this should work.

Would you also add an update to the Readme to document the new option?

**Comment by KhodorAmmar** [comment]
Yes, we've already testing the code with extra methods and it's working perfectly.
Sure I'll update Readme tomorrow and update the pull request, thanks!

**Comment by KhodorAmmar** [comment]
Updated

**Comment by colestrode** [comment]
I confirmed the tests passed and we still have 100% coverage (I would _love_ to automate this... hopefully soon!). @anonrig what do you think about merging this in?

**Comment by anonrig** [comment]
Seems good to me!

**Comment by anonrig** [comment]
@benbrown Can you bump the version?

**Comment by colestrode** [comment]
The `npm version` command is great for this. I recommend a minor version bump since this is a new feature.

**Pull request merged**
