### PR TITLE
Fix authentification process for botkit

### PR DESCRIPTION
**Pull request by pavel-kurnosov**
Botkit assume that get function should return null, not empty object, if there is no data in the store.
Otherwise it is fail

### CODE REVIEW

**Comment by colestrode** [comment]
Nice! You'll also need to update the test "should handle falsy result" to expect null instead of an object.

**Comment by pavel-kurnosov** [comment]
Ah Sorry forgot about tests

**Comment by pavel-kurnosov** [comment]
Ready for merge all tests are passed

**Comment by anonrig** [comment]
Good job! Sorry for the inconvenience. @pavel-kurnosov

**Pull request merged**
